In [2]:
import numpy as np

In [3]:
arr = np.array([10,20,30])

In [4]:
arr

array([10, 20, 30])

In [5]:
arr.ndim #it denotes the number of rows

1

In [6]:
arr.size #it denotes the number of elements in array

3

In [7]:
arr.shape #it denotes the sequece of integers in the each row when array is 1D array

(3,)

In [8]:
arr2 =  np.array([
    [1,2,3],
    [4,5,8],
    [6,7,8],
    [9,0,7]
])

In [9]:
arr2.shape #it denotes the number of rows and columns in a array

(4, 3)

In [10]:
arr3 = np.array([10,20,30])

In [11]:
arr3 #by default it is in default datatype

array([10, 20, 30])

In [12]:
arr3 = np.array([10,20,30], dtype = float)

In [13]:
arr3 #we can change the data type of each element by using dtype attribute 

array([10., 20., 30.])

In [14]:
np.zeros(arr.size)#method to fill the array with zeros 

array([0., 0., 0.])

In [15]:
np.ones(arr2.shape, dtype = int) #method to fill the array with ones 

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [16]:
x = np.arange(20,1,-1) #it is the method that creates the array with the sequence of number 

In [17]:
x

array([20, 19, 18, 17, 16, 15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,
        3,  2])

In [18]:
arr3

array([10., 20., 30.])

In [19]:
arr4 = np.array([
    [1,2,3,4],
    [5,6,7,8],
    [9,10,11,12],
    [13,14,15,16]
])

In [20]:
arr4[1]

array([5, 6, 7, 8])

In [21]:
arr4[1,2]

7

In [22]:
len(arr4)

4

In [23]:
arr3

array([10., 20., 30.])

In [24]:
np.concatenate((arr4,arr4),axis = 0 )

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [25]:
z = np.concatenate((arr4,arr4),axis= 1)

In [26]:
z

array([[ 1,  2,  3,  4,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  5,  6,  7,  8],
       [ 9, 10, 11, 12,  9, 10, 11, 12],
       [13, 14, 15, 16, 13, 14, 15, 16]])

In [27]:
z.reshape(8,4)

array([[ 1,  2,  3,  4],
       [ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [13, 14, 15, 16]])

In [28]:
len(z)

4

In [29]:
z.ndim

2

In [30]:
z.shape

(4, 8)

In [31]:
z.size

32

In [32]:
z

array([[ 1,  2,  3,  4,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  5,  6,  7,  8],
       [ 9, 10, 11, 12,  9, 10, 11, 12],
       [13, 14, 15, 16, 13, 14, 15, 16]])

In [33]:
z.shape

(4, 8)

In [35]:
tans = z.transpose()

In [37]:
tans

array([[ 1,  5,  9, 13],
       [ 2,  6, 10, 14],
       [ 3,  7, 11, 15],
       [ 4,  8, 12, 16],
       [ 1,  5,  9, 13],
       [ 2,  6, 10, 14],
       [ 3,  7, 11, 15],
       [ 4,  8, 12, 16]])

In [36]:
tans.shape 

(8, 4)

In [39]:
tans.sort()

In [40]:
tans

array([[ 1,  5,  9, 13],
       [ 2,  6, 10, 14],
       [ 3,  7, 11, 15],
       [ 4,  8, 12, 16],
       [ 1,  5,  9, 13],
       [ 2,  6, 10, 14],
       [ 3,  7, 11, 15],
       [ 4,  8, 12, 16]])